ISICWeb/Areas/Antecedentes/Controllers/AntecedentesIdgxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ISIC.Entities;
using ISICWeb.Areas.Antecedentes.Models;
using ISICWeb.Services;
using MPBA.DataAccess;

namespace ISICWeb.Areas.Antecedentes.Controllers
{
    [Audit]
    [Autorizar(Roles = "Administrador, Antecedentes")]
    public class AntecedentesIdgxController : Controller
    {
        
        IRepository _repository;
        private IIdgxService _idgxService;

        public AntecedentesIdgxController(IRepository repository, IIdgxService idgxService)
        {
            _repository = repository;
            _idgxService = idgxService;
        }

        /// <summary>
        /// Trae los datos del prontuario en idgx ya sea por prontuariosic o con prioridad idgxprontuario 
        /// </summary>
        /// <param name="prontuariosic">busca el prontuario en idgx que tenga el prontuariosic indicado</param>
        /// <param name="idIdgxprontuario">trae el prontuario en idgx con id indicado, obviando el paramentro prontuariosic</param>
        /// <returns></returns>
        public ActionResult AltaModificacionProntuarioIDGx(string prontuariosic = "", string idIdgxprontuario = "",
            bool esNuevo = false)
        {
            IdgxProntuario idgxProntuario = null;
            if (!esNuevo)
            {
                if (idIdgxprontuario.Trim() == "")
                    idgxProntuario =
                        _repository.Set<IdgxProntuario>()
                            .SingleOrDefault(x => x.Prontuario.ProntuarioNro == prontuariosic);
                else
                {
                    idgxProntuario =
                        _repository.Set<IdgxProntuario>().FirstOrDefault(x => x.Id.ToString() == idIdgxprontuario);
                }
            }
            IdgxProntuarioViewModel prontuario = null;
            prontuario = _idgxService.TraerIdgxProntuarioViewModel(idgxProntuario, prontuariosic);
            return View(prontuario);

        }


        public bool BorrarDatosPersonales(int id)
        {
            bool borroBien = _idgxService.BorrarIdgxDatosPersonales(id);
            if (!borroBien)
                ModelState.AddModelError("", "No se pudieron borrar los datos de la persona");
            return borroBien;
        }




        public ActionResult BuscarProntuariosIdgx(string prontuariosic)
        {
            Session["prontuariosic"] = prontuariosic;
            Prontuario prontuario = _repository.Set<Prontuario>().FirstOrDefault(x => x.ProntuarioNro == prontuariosic);
            if (prontuario == null)
            {
                prontuario = new Prontuario
                {
                    ProntuarioNro = prontuariosic
                };
            }
            return View("ListadoProntuariosIdgx", prontuario);
        }




        public int GuardarIdgxProntuario(string idIdgxProntuario, string prontuariopf, string idtipoprontuario, string prontuariosic)
        {
            return _idgxService.GuardarIdgxProntuario(idIdgxProntuario, prontuariopf, idtipoprontuario, prontuariosic);


        }



        public ActionResult AltaModificacionDatosPersonalesIdGx(int idIdgxprontuario, int idIdgxdatospersonales = 0)
        {
            IdgxDatosPersonalesViewModel datosPersona = null;
            if (idIdgxdatospersonales == 0) //nuevo dato
            {
                datosPersona = new IdgxDatosPersonalesViewModel
                {
                    Id = 0,
                    FechaInforme = DateTime.Now.ToString("dd/MM/yyyy"),
                    idIdgxProntuario = idIdgxprontuario,
                    TipoDocumentoList = new SelectList(_repository.Set<ClaseTipoDNI>().ToList(), "Id", "descripcion"),
                    ProvinciaList = new SelectList(_repository.Set<Provincia>().ToList(), "Id", "ProvinciaNombre"),

                };
            }
            else //modificando 
            {
                datosPersona = _idgxService.TraerIdgxDatosPersona(idIdgxdatospersonales,
                    idIdgxprontuario);
            }

            ViewBag.prontuarioidgx = _repository.Set<IdgxProntuario>().Single(x=>x.Id==idIdgxprontuario).ProntuarioPF;

            return View("AltaModificacionDatosPersonalesIDGx", datosPersona);
        }

        [HttpPost]
        public ActionResult GuardarDatosPersonalesIdGx(IdgxDatosPersonalesViewModel datosPersona)
        {
            int idIdgxDatosPersonales = _idgxService.GuardarIdgxDatosPersona(datosPersona, User);
            // ViewData["idIdgxdatospersonales"] = idIdgxDatosPersonales;
            datosPersona.Id = idIdgxDatosPersonales;
            if (idIdgxDatosPersonales > 0)
            {
                datosPersona = _idgxService.TraerIdgxDatosPersona(idIdgxDatosPersonales, datosPersona.idIdgxProntuario);
                return PartialView("_IdgxDelitosAsociados", datosPersona);
            }
            else
            {
                return PartialView("_IdgxDelitosAsociados", new IdgxDatosPersonalesViewModel());
            }
        }

        //public ActionResult MostrarIdgxDelitosAsociados(int idIdgxDatosPersona)
        //{
        //    IdgxDatosPersona persona = _repository.Set<IdgxDatosPersona>().SingleOrDefault(x => x.Id == idIdgxDatosPersona);
        //    IEnumerable<IdgxDetalle> delitos = null;
        //    if (persona != null && persona.Delitos != null)
        //        delitos = persona.Delitos;

        //    return PartialView("_IdgxDelitosAsociados",delitos);
        //}
        public ActionResult AltaModificacionDelitoIdgx(int idIdgxdatospersonales, int idIdgxdelito = 0)
        {
            IdgxDelitoViewModel delito = null;
            if (idIdgxdelito == 0) //nuevo
            {
                IdgxDatosPersona datosPersona =
                    _repository.Set<IdgxDatosPersona>().Single(x => x.Id == idIdgxdatospersonales);
                ViewBag.prontuarioidgx = _repository.Set<IdgxProntuario>().Single(x => x.Id == datosPersona.IdgxProntuario.Id).ProntuarioPF;
                delito = new IdgxDelitoViewModel
                {
                    Id = 0,
                    CodigoRestriccionList =
                        new SelectList(_repository.Set<ClaseCodigoRestriccionPoliciaFederal>().ToList(), "Id",
                            "descripcion"),
                    CodigoRestriccionPF = "0",
                    idIdgxdatospersonales = idIdgxdatospersonales,
                    idIdgxprontuario = (datosPersona.IdgxProntuario == null ? 0 : datosPersona.IdgxProntuario.Id)
                    
                };
                
            }
            else
            {
                delito = _idgxService.TraerIdgxDelito(idIdgxdelito);
                ViewBag.prontuarioidgx = _repository.Set<IdgxProntuario>().Single(x => x.Id == delito.idIdgxprontuario).ProntuarioPF;
            }
            
            return View("AltaModificacionDelitoIdgx", delito);
        }

        [HttpPost]
        public int GuardarDelitoIdgx(IdgxDelitoViewModel delito)
        {
            int idDelito = _idgxService.GuardarIdgxDelito(delito,User);
            delito.CodigoRestriccionList =
                new SelectList(_repository.Set<ClaseCodigoRestriccionPoliciaFederal>().ToList(), "Id", "descripcion");
            IdgxDatosPersonalesViewModel datosPersona = _idgxService.TraerIdgxDatosPersona(delito.idIdgxdatospersonales, delito.idIdgxprontuario);
            // return View("CargaDatosPersonalesIDGx", datosPersona);
            delito.Id = idDelito;
            //return View("CargarDelitoIdgx", delito);
            return idDelito;

        }

        [ChildActionOnly]
        public ActionResult MostrarIdgxDelitosAsociados(int idIdgxDatosPersona)
        {

            IdgxDatosPersona persona = _repository.Set<IdgxDatosPersona>().SingleOrDefault(x => x.Id == idIdgxDatosPersona);
            IdgxDatosPersonalesViewModel datospersona = null;

            if (persona != null)
                datospersona = _idgxService.TraerIdgxDatosPersona(idIdgxDatosPersona, persona.IdgxProntuario.Id);

            return PartialView("_IdgxDelitosAsociados", datospersona);
        }

        public bool BorrarDelitoIdgx(int id)
        {
            bool borroBien = _idgxService.BorrarIdgxDelito(id, User);
            if (!borroBien)
                ModelState.AddModelError("", "No se pudo borrar el delito de idgx");
            return borroBien;
        }

        public bool BorrarProntuarioIdgx(int id)
        {
            bool borroBien = _idgxService.BorrarProntuarioIdgx(id, User);
            if (!borroBien)
                ModelState.AddModelError("", "No se pudo borrar el delito de idgx");
            return borroBien;
        }



        public ActionResult MostrarDatosIdgx(int id)
        {
            IdgxProntuario prontuario = _repository.Set<IdgxProntuario>().Single(x => x.Id == id);
            IdgxProntuarioViewModel prontuarioviewmodel = _idgxService.TraerIdgxProntuarioViewModel(prontuario,prontuario.Prontuario.ProntuarioNro);
            return View("ListaDatosPersonalesIDGx", prontuarioviewmodel);
        }

     

    }
}

ISICWeb/Areas/Antecedentes/Views/AntecedentesIdgx/ListaDatosPersonalesIDGx.cshtml
@using System.ServiceModel.Security
@model ISICWeb.Areas.Antecedentes.Models.IdgxProntuarioViewModel

@{ string url = Session["CurrentUrl"] != null ? Session["CurrentUrl"].ToString() : @Url.Action("Index","Antecedentes"); }


<div class="container-detalle" style="margin-bottom: 80px;">
    <div class="row wow fadeInDown animated">
        <ol class="breadcrumb hidden-xs tile-light" style="float:left!important">
            <li>@Html.ActionLink("Búsqueda", "Index", "Antecedentes")</li>
            <li><a href="@url">Resultados</a></li>
            <li>@Html.ActionLink("Prontuarios", "BuscarProntuariosIdgx", new {prontuariosic = Model.prontuariosic})</li>
            <li>@Html.ActionLink("Prontuario", "AltaModificacionProntuarioIDGx", new { prontuariosic = Model.prontuariosic, idIdgxprontuario = Model.Id, esNuevo = false })</li>
            <li class="active">Lista Datos Pers.</li>
        </ol>


    </div>
    <div class="center wow fadeInDown animated tile-light">
        <h1>Datos Personales según IDGx</h1>
    </div>



    @if (Model != null)
    {
        Html.RenderAction("MostrarDatosImputado", "Antecedentes", new {idIdgxprontuario = Model.Id});

    }




    <div class="panel panel-default tile wow fadeInDown animated">
        <div class="panel-heading">


            <h3>Datos Personales Asociados al Prontuario de IDGx nro. @Model.ProntuarioPF</h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <table id="tablaDatosPersonales" class="table  table-bordered table-hover  table-striped tile tabla" cellspacing="0" width="100%">
                        <thead>
                        <tr>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Apellido
                            </th>

                            <th>
                                Documento
                            </th>
                            <th>
                                Fecha Nacimiento
                            </th>

                            <th>
                                Localidad Nac.
                            </th>

                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @if (Model != null && Model.DatosPersona != null)
                        {
                            foreach (var item in Model.DatosPersona)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nombre)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Apellido)
                                    </td>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.DocumentoNumero)
                                    </td>
                                    <td>
                                        
                                        @if (item.FechaNacimiento != null)
                                        {
                                            var fenac = item.FechaNacimiento.ToString().Substring(0, 10);
                                            @fenac;

                                        }
                                    </td>


                                    <td>
                                        @if (item.LocalidadNacimiento != null)
                                        {
                                            Html.DisplayFor(modelItem => item.LocalidadNacimiento.LocalidadNombre);
                                        }
                                    </td>


                                    <td>
                                        @Html.ActionLink("Editar", "AltaModificacionDatosPersonalesIdGx", new { idIdgxdatospersonales = item.Id, idIdgxprontuario = Model.Id }, new { @class = "btn btn-alt btn-sm", onclick = "showPageLoadingSpinner();" })

                                        <input type="button" class="btn btn-alt btn-sm" id="btnBorrarDatosPersonales" data-id="@item.Id"  value="Borrar"/>
                                    </td>
                                </tr>

                            }
                        }
                        </tbody>

                    </table>
                </div>




            </div>
        </div>


    </div>
</div>

@section footer
{
    <div class="col-md-2 col-sm-2 col-xs-6">
        @Html.ActionLink("Volver", "AltaModificacionProntuarioIDGx", new { prontuariosic = Model.prontuariosic, idIdgxprontuario = Model.Id, esNuevo = false }, new { @class = "btn btn-alt btn-lg ", onclick = "showPageLoadingSpinner();" })
        @*<a class="btn btn-lg btn-alt volver" href='@url' title=" volver" onclick="showPageLoadingSpinner();" type="button">
            Volver
        </a>*@
    </div>
    <div class="col-md-6 col-md-offset-4 col-sm-2 col-sm-offset-4 col-xs-6">
        @if (Model != null)
        {
            @Html.ActionLink("Nuevo Dato Personal", "AltaModificacionDatosPersonalesIdGx", new { idIdgxprontuario = Model.Id }, new { @class = "btn btn-lg btn-alt", onclick = "showPageLoadingSpinner();" })
        }
    </div>

}




@section scripts
  {
    <script>

        $(function () {
            $("#btnGuardarIdgxProntuario").on("click", function () {
                var prontuariopf = $("#ProntuarioPF").val();
                var idtipoprontuario = $("#TipoProntuarioPF").val();
                var url = '@Url.Content("GuardarIdgxProntuario")?ididgxprontuario=' +@Model.Id +'&prontuariopf=' + prontuariopf+'&idtipoprontuario='+idtipoprontuario;
                $.get(url, null, function (data) {
                    if (data === "True")
                        alertify.success("Prontuario guardado correctamente");
                    else
                        alertify.error("No se pudo guardar el prontuario");

                });
            });
        });

        $(document).ready(function () {
            $('#tablaDatosPersonales').dataTable({
                "dom": '<"row"<"col-md-12"ipT>><"clear">rt<"bottom"><"clear">',
                "tableTools": {
                    "aButtons": []
                    //"sSelectedClass": "row_selected",
                    //"sRowSelect": "single",
                    //"fnRowSelected": function(nodes) {
                    //    var id = nodes[0].id;


                    //},
                    //"fnRowDeselected": function(nodes) {


                    //}
                },
                "columnDefs": [
                 {
                     "targets": 4,
                     "sortable": false
                 },
                 {
                     "targets": 5,
                     "sortable": false
                 }
                ],
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
            });
            $('#tablaDatosPersonales tbody').on('click', '#btnBorrarDatosPersonales', function () {
                var id = $(this).data("id");
                var table = $('#tablaDatosPersonales').DataTable();
                var row = table.row($(this).parents('tr'));
                alertify.confirm("Borrar Imputado", "Seguro que desea borrar?", function () {

                    var url = '@Url.Action("BorrarDatosPersonales","AntecedentesIdgx")?id=' + encodeURI(id);
                    $.get(url, null, function (data) {
                        if (data === "True") {

                            row.remove().draw();
                            alertify.success("Imputado borrado correctamente");


                        } else {
                            alertify.error("Error al borrar");
                        }
                    });

                }, null)
             .set('labels', { cancel: 'Cancelar' })
             .set('defaultFocus', 'cancel');
            });
        });
    </script>
}

ISICWeb/Areas/Antecedentes/Views/AntecedentesIdgx/ListadoProntuariosIdgx.cshtml
@model ISIC.Entities.Prontuario
@{ string url = Session["CurrentUrl"] != null ? Session["CurrentUrl"].ToString() : @Url.Action("Index","Antecedentes"); }

<div class="row wow fadeInDown animated">
    <ol class="breadcrumb hidden-xs tile-light" style="float:left!important">
        <li>@Html.ActionLink("Búsqueda", "Index", "Antecedentes")</li>
        <li><a href="@url">Resultados</a></li>
        <li class="active">Prontuarios</li>
    </ol>


</div>
<div class=" center wow fadeInDown animated tile-light">
    <h1>
        Prontuarios en IDGx
    </h1>
</div>
<div class="tile   wow fadeInDown animated">
    @{
        Html.RenderAction("MostrarDatosImputado", "Antecedentes", new { prontuarioSic = Model.ProntuarioNro });

    }
</div>

<div class="tile tile  wow fadeInDown animated" style="margin-bottom: 80px;">

    <div class="panel panel-default ">
        <div class="panel-heading">
            <h4>
                Listado de prontuarios en IDGx
            </h4>
        </div>
    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <table id="tablaProntuarios" class="table  table-bordered table-hover  table-striped  tabla" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>
                                Tipo de Prontuario
                            </th>
                            <th>
                                Prontuario SIC
                            </th>
                            <th>
                                Prontuario PF
                            </th>
                            <th>

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.ProntuariosIdgx != null)
                        {
                            foreach (var item in Model.ProntuariosIdgx.Where(x => x.Baja != true))
                            {
                                <tr>
                                    <td>
                                        @if (item.tipoprontuario != null)
                                        {
                                            @Html.DisplayFor(modelItem => item.tipoprontuario.descripcion)
                                        }
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ProntuarioPF)
                                    </td>
                                    <td>
                                        @if (item.Prontuario != null)
                                        {
                                            @Html.DisplayFor(modelItem => item.Prontuario.ProntuarioNro)
                                        }
                                    </td>


                                    <td>
                                        @Html.ActionLink("Editar", "AltaModificacionProntuarioIDGx", new { prontuariosic = Model.ProntuarioNro, idIdgxprontuario = item.Id, esNuevo = false }, new { @class = "btn btn-alt btn-sm ", onclick = "showPageLoadingSpinner();" })
                                        <input type="button" class="btn btn-alt btn-sm" id="btnBorrarProntuarioIdgx" data-id="@item.Id" value="Borrar" />
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-md-12">
                        <div class="pull-right">

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>



</div>


@section footer
{
    <div class="col-md-2 col-sm-2 col-xs-6">
        @*<a class="btn btn-lg btn-alt volver" href='#' onclick=' ' title=" volver" type="button">
                Volver
            </a>*@
        <a class="btn btn-lg btn-alt volver" href='@url' title=" volver" onclick="showPageLoadingSpinner();" type="button">
            Volver
        </a>
    </div>
    <div class="col-md-6 col-md-offset-4 col-sm-2 col-sm-offset-4 col-xs-6">
        @if (Model != null)
        {
            @Html.ActionLink("Nuevo Prontuario", "AltaModificacionProntuarioIDGx", new { prontuariosic = Model.ProntuarioNro, esNuevo = true }, new { @class = "btn btn-alt btn-lg ", onclick = "showPageLoadingSpinner();" })
        }


    </div>

}






<script>
    $(document).ready(function () {
        $('#tablaProntuarios').dataTable({
            "dom": '<"row"<"col-md-12"ipT>><"clear">rt<"bottom"><"clear">',
            "tableTools": {
                "aButtons": [],

            },
            "columnDefs": [
                {
                    "targets": 3,
                    "sortable": false
                }
            ],
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
        $('#tablaProntuarios tbody').on('click', '#btnBorrarProntuarioIdgx', function () {
            
            var id = $(this).data("id");
            var table = $('#tablaProntuarios').DataTable();
            var row = table.row($(this).parents('tr'));
                
            alertify.confirm("Borrar Prontuario en IDGx", "Seguro que desea borrar?", function () {

                var url = '@Url.Action("BorrarProntuarioIdgx","AntecedentesIdgx")/' + encodeURI(id);
                $.get(url, null, function (data) {
                    if (data === "True") {
                        row.remove().draw();
                        alertify.success("Prontuario borrado correctamente");
                        

                    } else {
                        alertify.error("Error al borrar");
                    }
                });

            }, null)
         .set('labels', { cancel: 'Cancelar' })
         .set('defaultFocus', 'cancel');
        });

    });

  
</script>