ISICWeb/Areas/Antecedentes/Controllers/AntecedentesGnaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ISIC.Entities;
using ISICWeb.Areas.Antecedentes.Models;
using ISIC.Services;
using ISICWeb.Areas.PortalSIC.Services;
using ISICWeb.Services;
using MPBA.DataAccess;

namespace ISICWeb.Areas.Antecedentes.Controllers
{
    [Audit]
    [Autorizar(Roles = "Administrador, Antecedentes")]
    public class AntecedentesGnaController : Controller
    {
        IRepository _repository;
        private IGnaService _gnaService;

       public AntecedentesGnaController(IRepository repository, IGnaService gnaService)
        {
            _repository = repository;
            _gnaService = gnaService;
        }

       public ActionResult AltaModificacionGNA(string prontuariosic = "", int idGNA=0)
       {
           GNAViewModel model = _gnaService.LlenarViewModelDesdeBase(prontuariosic, idGNA);
           return View(model);
       }

       public ActionResult BuscarFichasGNA(string prontuariosic)
       {
           Session["prontuariosic"] = prontuariosic;
           Prontuario prontuario = _repository.Set<Prontuario>().FirstOrDefault(x => x.ProntuarioNro == prontuariosic);
           if (prontuario == null)
           {
               prontuario = new Prontuario
               {
                   ProntuarioNro = prontuariosic
               };
           }
           return View("ListadoGNAs", prontuario);
       }


       public bool BorrarFichaGNA(int id)
       {
           bool borroBien = _gnaService.BorrarFichaGNA(id, User);
           if (!borroBien)
               ModelState.AddModelError("", "No se pudo borrar la ficha de GNA");
           return borroBien;
       }

       [HttpPost]
       public ActionResult GuardarDatosGNA(GNAViewModel model)
       {
           string errores = "";
           if (ModelState.IsValid)
           {
               errores = _gnaService.GuardarFichaGNA(model, User);
           }
           else
           {
               errores = string.Join("; ", ModelState.Values
                                         .SelectMany(x => x.Errors)
                                         .Select(x => x.ErrorMessage));
           }
           
           

           if (errores != "")
           {
               ModelState.AddModelError("", errores);
               return PartialView("_SummaryErrorGna", model);
           }
           return null;



       }

    }
}

ISICWeb/Areas/Antecedentes/Views/AntecedentesGna/AltaModificacionGNA.cshtml
@model ISICWeb.Areas.Antecedentes.Models.GNAViewModel
@{ string url = Session["CurrentUrl"] != null ? Session["CurrentUrl"].ToString() : @Url.Action("Index","Antecedentes"); }

@using (Ajax.BeginForm("GuardarDatosGNA", "Antecedentes",
  new AjaxOptions
                {
                    UpdateTargetId = "divValidation",
                    HttpMethod = "Post",
                    OnBegin = "onGuardarBegin",
                    OnComplete = "onGuardarComplete",
                    OnSuccess = "onGuardarSuccess"
                },
                new { id = "frmGuardarDatosGna" }))
{    @Html.AntiForgeryToken()

    <div class="row wow fadeInDown animated">
        <ol class="breadcrumb hidden-xs tile-light" style="float: left !important">
            <li>@Html.ActionLink("Búsqueda", "Index", "Antecedentes")</li>
            <li><a href="@url">Resultados</a></li>
            <li>@Html.ActionLink("Listado GNA", "BuscarFichasGNA", new { prontuariosic = Model.Prontuario.ProntuarioNro }, new { onclick = "showPageLoadingSpinner();" })</li>
            <li class="active">Carga GNA</li>
        </ol>
    </div>
    <div class=" center wow fadeInDown animated tile-light">
        <h3>
            Carga datos de GNA
        </h3>
    </div>
    <div class="tile   wow fadeInDown animated">
        @{
  

        }
    </div>

    if (Model != null)
    {
        Html.RenderAction("MostrarDatosImputado", "Antecedentes", new { prontuarioSic = Model.Prontuario.ProntuarioNro });

    }

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="panel panel-default tile wow fadeInDown animated" style="margin-bottom: 80px;">
        <div class="panel-heading">
            @if (Model.Id > 0)
            {
                <h4><b style="color: red;">Modificación</b> Datos de GNA</h4>
            }
            else
            {
                <h4>Carga Nuevos Datos de GNA</h4>
            }
        </div>
        <div class="panel-body">


            <div class="row wow fadeInDown animated">

                <div class="col-xs-4">
                    @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label  " })
                    @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label  " })
                    @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.idClaseSexo, htmlAttributes: new { @class = "control-label  " })
                    @Html.DropDownListFor(model => model.idClaseSexo, Model.ClaseSexoList as IEnumerable<SelectListItem>, new { @class = "form-control" })
                </div>
            </div>
            <div class="row wow fadeInDown animated">
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.idClaseTipoDNI, htmlAttributes: new { @class = "control-label  " })
                    @Html.DropDownListFor(model => model.idClaseTipoDNI, Model.ClaseTipoDNIList as IEnumerable<SelectListItem>, new { @class = "form-control" })
                </div>
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.DocumentoNumero, htmlAttributes: new { @class = "control-label  " })
                    @Html.EditorFor(model => model.DocumentoNumero, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DocumentoNumero, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.Juzgadointerviniente, htmlAttributes: new { @class = "control-label  " })
                    @Html.EditorFor(model => model.Juzgadointerviniente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Juzgadointerviniente, "", new { @class = "text-danger" })
                </div>


            </div>
            <div class="row wow fadeInDown animated">
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "control-label  " })

                    @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control datepicker fecha" } })
                    @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.ApellidoMadre, htmlAttributes: new { @class = "control-label  " })
                    @Html.EditorFor(model => model.ApellidoMadre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ApellidoMadre, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.Generado, htmlAttributes: new { @class = "control-label  " })
                    @Html.EditorFor(model => model.Generado, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Generado, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row wow fadeInDown animated">
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.NroLegajoGNA, htmlAttributes: new { @class = "control-label  " })
                    @Html.EditorFor(model => model.NroLegajoGNA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NroLegajoGNA, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.ExpteGNA, htmlAttributes: new { @class = "control-label  " })
                    @Html.EditorFor(model => model.ExpteGNA, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExpteGNA, "", new { @class = "text-danger" })
                </div>
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.Caratula, htmlAttributes: new { @class = "control-label  " })
                    @Html.EditorFor(model => model.Caratula, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Caratula, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row wow fadeInDown animated">
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.Asunto, htmlAttributes: new {@class = "control-label  "})
                    @Html.EditorFor(model => model.Asunto, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Asunto, "", new {@class = "text-danger"})
                </div>

                <div class="col-xs-4">
                    <div class="row">
                        <div class="col-md-3">
                            <br />
                            @Html.LabelFor(model => model.Captura, htmlAttributes: new {@class = "control-label  "})
                            @Html.CheckBoxFor(model => model.Captura)
                            @Html.ValidationMessageFor(model => model.Captura, "", new {@class = "text-danger"})


                        </div>
                        <div class="col-md-9">
                            @Html.LabelFor(model => model.FechaPedido, htmlAttributes: new {@class = "control-label  "})
                            @Html.EditorFor(model => model.FechaPedido, new {htmlAttributes = new {@class = "form-control datepicker fecha"}})
                            @Html.ValidationMessageFor(model => model.FechaPedido, "", new {@class = "text-danger"})


                        </div>
                    </div>


                </div>
                <div class="col-xs-4">
                    <div class="col-xs-4">
                        <br />
                        @Html.LabelFor(model => model.Vigente, htmlAttributes: new {@class = "control-label  "})
                        @Html.CheckBoxFor(model => model.Vigente)
                        @Html.ValidationMessageFor(model => model.Vigente, "", new {@class = "text-danger"})
                    </div>

                    <div class="col-xs-4">
                        <br />
                        @Html.LabelFor(model => model.ImpSalida, htmlAttributes: new {@class = "control-label  "})
                        @Html.EditorFor(model => model.ImpSalida)
                        @Html.ValidationMessageFor(model => model.ImpSalida, "", new {@class = "text-danger"})
                    </div>
                    <div class="col-xs-4">
                        <br />
                        @Html.LabelFor(model => model.Corroborado, htmlAttributes: new {@class = "control-label  "})
                        @Html.CheckBoxFor(model => model.Corroborado)
                        @Html.ValidationMessageFor(model => model.Corroborado, "", new {@class = "text-danger"})


                    </div>
                </div>
            </div>
            <div class="row wow fadeInDown animated">
                <div class="col-xs-4">
                    @Html.LabelFor(model => model.FechaInforme)
                    @Html.EditorFor(model => model.FechaInforme, new {htmlAttributes = new {@class = "form-control datepicker"}})
                    @Html.ValidationMessageFor(model => model.FechaInforme, "", new {@class = "text-danger"})
                </div>
            </div>

                    <div class="row">
                        <div class="col-md-12" id="divValidation">
                            @Html.HiddenFor(model => model.Prontuario.ProntuarioNro)
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)

                        </div>
                    </div>

                </div>
            </div>




            <nav class="navbar navbar-default navbar-fixed-bottom tile-dark">
                <div class="row">
                    <div class="  col-sm-3 col-xs-4">
                        @Html.ActionLink("Volver", "BuscarFichasGNA", new { prontuariosic = Model.Prontuario.ProntuarioNro }, new { @class = "btn btn-alt btn-lg", onclick = "showPageLoadingSpinner();" })


                    </div>
                    <div class="col-md-3 col-md-offset-2 col-sm-4 col-xs-8">
                        <div class="row ">
                            <div class="col-md-6 col-sm-6 col-xs-6">
                                <input type="submit" value="Guardar" class="btn btn-alt btn-lg fa-align-center" />
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-6">


                            </div>
                        </div>
                    </div>

                </div>

            </nav>
            }

            @section scripts
{
                <script>
                    //GUARDAR DATOS GNA
                    function onGuardarBegin() {
                        loader("Guardando, espere un momento...");
                    }

                    function onGuardarComplete() {
                        $.unblockUI();
                    }

                    function onGuardarSuccess(data) {
                        if (data == "") {
                            //alertify.success("Alta exitosa");
                            var url = '@Url.Content("BuscarFichasGNA")?prontuariosic=@Model.Prontuario.ProntuarioNro';
                            alertify.alert("Exito", "<i class='Exito'>Carga Exitosa</i>").set({
                                onclose: function () {

                                    showPageLoadingSpinner();
                                    location.href = url;

                                }
                            });

                            //$("#btnNuevoDelito").removeClass("hidden");
                            //$("#cartelSinDelitos").addClass("hidden");
                            //$("#Id").val($("#idIdgxdatospersonales").val());

                        } else {
                            alertify.error("Error en la carga");
                            //$("#btnNuevoDelito").addClass("hidden");
                            $("#cartelSinDelitos").removeClass("hidden");
                        }
                    }

                    //$('#FechaNacimiento').bind('keyup keypress blur change cut copy paste ', function () {
                    //    var validator = $("#frmGuardarDatosGna").validate();
                    //    validator.element(this);
                    //});

                    $(document).ready(function () {
                        $("#navFooter").hide();
                        //$(".fecha").mask("99/99/9999");
                    });
                </script>
            }

ISICWeb/Areas/Antecedentes/Views/AntecedentesGna/DetalleGNAs.cshtml
@model ISIC.Entities.Prontuario
@{ string url = Session["CurrentUrl"] != null ? Session["CurrentUrl"].ToString() : @Url.Action("Index"); }

<div class="row wow fadeInDown animated">
    <ol class="breadcrumb hidden-xs tile-light" style="float: left !important">
        <li>@Html.ActionLink("Búsqueda", "Index", "Antecedentes")</li>
        <li><a href="@url">Resultados</a></li>
        <li class="active">Lista GNA</li>
    </ol>
</div>
<div class=" center wow fadeInDown animated tile-light">
    <h1>
        Fichas de GNA
    </h1>
</div>
<div class="tile   wow fadeInDown animated">
    @{
        Html.RenderAction("MostrarDatosImputado", "Antecedentes", new { prontuarioSic = Model.ProntuarioNro });

    }
</div>


<div class="tile tile  wow fadeInDown animated" style="margin-bottom: 80px;">

    <div class="panel panel-default ">
        <div class="panel-heading">
            <h4>
                Listado de fichas de GNA
            </h4>
        </div>
    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <table id="tablaGNAs" class="table  table-bordered table-hover  table-striped  tabla" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>
                                Apellido
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Documento Nro.
                            </th>
                            <th>
                                Caratula
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.DatosGNA != null)
                        {
                            foreach (var item in Model.DatosGNA.Where(x => x.Baja != true))
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Apellido)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nombre)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DocumentoNumero)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Caratula)
                                    </td>
                                    <td style="text-align: right">
                                        @Html.ActionLink("Editar", "AltaModificacionGNA", new { prontuariosic = Model.ProntuarioNro, idGNA = item.Id, esNuevo = false }, new { @class = "btn btn-alt btn-sm " })
                                        <input type="button" class="btn btn-alt btn-sm" id="btnBorrarGNA" data-id="@item.Id" value="Borrar" />
                                    </td>
                                </tr>
                            }
                        }

                    </tbody>
                </table>
                <div class="row">
                    <div class="col-md-12">
                        <div class="pull-right">

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>



</div>

@section footer
{
    <div class="col-md-2 col-sm-2 col-xs-6">
        @*<a class="btn btn-lg btn-alt volver" href='#' onclick=' ' title=" volver" type="button">
                Volver
            </a>*@
        <a class="btn btn-lg btn-alt volver" href='@url' title=" volver" onclick="showPageLoadingSpinner();" type="button">
            Volver
        </a>
    </div>
    <div class="col-md-6 col-md-offset-4 col-sm-2 col-sm-offset-4 col-xs-6">
        @if (Model != null)
        {
            @Html.ActionLink("Nuevo", "AltaModificacionGNA", new { prontuariosic = Model.ProntuarioNro, esNuevo = true }, new { @class = "btn btn-alt btn-lg ", onclick = "showPageLoadingSpinner();" })
        }


    </div>

}


<script>
    $(document).ready(function () {
        $('#tablaGNAs').dataTable({
            "dom": 'pT<"clear"i>rt<"bottom"><"clear">',
            "tableTools": {
                "aButtons": [],

            },
            "columnDefs": [
                {
                    "targets": 4,
                    "sortable": false
                }
            ],
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
        $('#tablaGNAs tbody').on('click', '#btnBorrarGNA', function () {

            var id = $(this).data("id");
            var table = $('#tablaGNAs').DataTable();
            var row = table.row($(this).parents('tr'));

            alertify.confirm("Borrar ficha de GNA", "Seguro que desea borrar?", function () {

                var url = '@Url.Action("BorrarFichaGNA","Antecedentes")/' + encodeURI(id);
                $.get(url, null, function (data) {
                    if (data === "True") {
                        row.remove().draw();
                        alertify.success("Ficha de GNA borrada correctamente");


                    } else {
                        alertify.error("Error al borrar");
                    }
                });

            }, null)
         .set('labels', { cancel: 'Cancelar' })
         .set('defaultFocus', 'cancel');
        });

    });


</script>

ISICWeb/Areas/Antecedentes/Views/AntecedentesGna/ListadoGNAs.cshtml
@model ISIC.Entities.Prontuario
@{ string url = Session["CurrentUrl"] != null ? Session["CurrentUrl"].ToString() : @Url.Action("Index","Antecedentes"); }

<div class="row wow fadeInDown animated">
    <ol class="breadcrumb hidden-xs tile-light" style="float: left !important">
        <li>@Html.ActionLink("Búsqueda", "Index", "Antecedentes")</li>
        <li><a href="@url">Resultados</a></li>
        <li class="active">Lista GNA</li>
    </ol>
</div>
<div class=" center wow fadeInDown animated tile-light">
    <h1>
        Fichas de GNA
    </h1>
</div>
<div class="tile   wow fadeInDown animated">
    @{
        Html.RenderAction("MostrarDatosImputado", "Antecedentes", new { prontuarioSic = Model.ProntuarioNro });

    }
</div>


<div class="tile tile  wow fadeInDown animated" style="margin-bottom: 80px;">

    <div class="panel panel-default ">
        <div class="panel-heading">
            <h4>
                Listado de fichas de GNA
            </h4>
        </div>
    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <table id="tablaGNAs" class="table  table-bordered table-hover  table-striped  tabla" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>
                                Apellido
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Documento Nro.
                            </th>
                            <th>
                                Caratula
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.DatosGNA != null)
                        {
                            foreach (var item in Model.DatosGNA.Where(x => x.Baja != true))
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Apellido)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nombre)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DocumentoNumero)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Caratula)
                                    </td>
                                    <td style="text-align: right">
                                        @Html.ActionLink("Editar", "AltaModificacionGNA", new { prontuariosic = Model.ProntuarioNro, idGNA = item.Id }, new { @class = "btn btn-alt btn-sm ", onclick = "showPageLoadingSpinner();" })
                                        <input type="button" class="btn btn-alt btn-sm" id="btnBorrarGNA" data-id="@item.Id" value="Borrar" />
                                    </td>
                                </tr>
                            }
                        }

                    </tbody>
                </table>
                <div class="row">
                    <div class="col-md-12">
                        <div class="pull-right">

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>



</div>

@section footer
{
    <div class="col-md-2 col-sm-2 col-xs-6">
        @*<a class="btn btn-lg btn-alt volver" href='#' onclick=' ' title=" volver" type="button">
                Volver
            </a>*@
        <a class="btn btn-lg btn-alt volver" href='@url' title=" volver" onclick="showPageLoadingSpinner();" type="button">
            Volver
        </a>
    </div>
    <div class="col-md-6 col-md-offset-4 col-sm-2 col-sm-offset-4 col-xs-6">
        @if (Model != null)
        {
            @Html.ActionLink("Nuevo", "AltaModificacionGNA", new { prontuariosic = Model.ProntuarioNro}, new { @class = "btn btn-alt btn-lg ", onclick = "showPageLoadingSpinner();" })
        }


    </div>

}


<script>
    $(document).ready(function () {
        $('#tablaGNAs').dataTable({
            "dom": '<"row"<"col-md-12"ipT>><"clear">rt<"bottom"><"clear">',
            "tableTools": {
                "aButtons": [],

            },
            "columnDefs": [
                {
                    "targets": 4,
                    "sortable": false
                }
            ],
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
        $('#tablaGNAs tbody').on('click', '#btnBorrarGNA', function () {

            var id = $(this).data("id");
            var table = $('#tablaGNAs').DataTable();
            var row = table.row($(this).parents('tr'));

            alertify.confirm("Borrar ficha de GNA", "Seguro que desea borrar?", function () {

                var url = '@Url.Action("BorrarFichaGNA","AntecedentesGna")/' + encodeURI(id);
                $.get(url, null, function (data) {
                    if (data === "True") {
                        row.remove().draw();
                        alertify.success("Ficha de GNA borrada correctamente");


                    } else {
                        alertify.error("Error al borrar");
                    }
                });

            }, null)
         .set('labels', { cancel: 'Cancelar' })
         .set('defaultFocus', 'cancel');
        });

    });


</script>

ISICWeb/Areas/Antecedentes/Views/AntecedentesGna/_SummaryErrorGna.cshtml
@model ISICWeb.Areas.Antecedentes.Models.GNAViewModel
@Html.HiddenFor(x => x.Prontuario.Id)
@Html.HiddenFor(x => x.Id)
@Html.HiddenFor(x => x.Prontuario.ProntuarioNro)
@Html.ValidationSummary()