ISICWeb/Areas/Antecedentes/Controllers/AntecedentesAfisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ISIC.Entities;
using ISICWeb.Areas.Antecedentes.Models;
using ISICWeb.Services;
using MPBA.DataAccess;

namespace ISICWeb.Areas.Antecedentes.Controllers
{
    public class AntecedentesAfisController : Controller
    {
        IRepository _repository;
        private AfisService _afisService;

        public AntecedentesAfisController(IRepository repository, AfisService afisService)
        {
            _repository = repository;
            _afisService = afisService;
        }



        [HttpPost]
        public ActionResult GuardarDatosAfis(AFISViewModel model)
        {
            string errores = "";
            if (ModelState.IsValid)
            {
                errores = _afisService.GuardarFichaAFIS(model);
            }
            else
            {
                errores = string.Join("; ", ModelState.Values
                                          .SelectMany(x => x.Errors)
                                          .Select(x => x.ErrorMessage));
            }

            if (errores != "")
            {
                ModelState.AddModelError("", errores);
                return PartialView("_SummaryErrorAfis", model);
            }
            return null;
        }


        public ActionResult BuscarFichasAFIS(string prontuariosic)
        {
            Session["prontuariosic"] = prontuariosic;
            Prontuario prontuario = _repository.Set<Prontuario>().FirstOrDefault(x => x.ProntuarioNro == prontuariosic);
            if (prontuario == null)
            {
                prontuario = new Prontuario
                {
                    ProntuarioNro = prontuariosic
                };
            }
            return View("ListadoAFIS", prontuario);
        }

        
        public ActionResult AltaModificacionAFIS(string prontuariosic,int idAfis=0)
        {

            AFISViewModel model = _afisService.LlenarViewModelDesdeBase(prontuariosic, idAfis);
          
            return View(model);
        }

        public bool BorrarFichasAFIS(int id)
        {
            bool borroBien = _afisService.BorrarFichaAFIS(id);
            if (!borroBien)
                ModelState.AddModelError("", "No se pudo borrar la ficha de AFIS");
            return borroBien;
        }

        //public ActionResult CargarAfis(string prontuariosic)
        //{
        //    ViewBag.SexoList = new SelectList(_repository.Set<ClaseSexo>().ToList(), "Id", "descripcion");
        //    AFIS afis = _repository.Set<AFIS>().SingleOrDefault(x => x.Prontuario.ProntuarioNro == prontuariosic);
        //    if (afis == null)
        //        afis = new AFIS
        //        {
        //            Sexo = _repository.Set<ClaseSexo>().Single(x => x.Id == 0),
        //            Prontuario = new Prontuario { ProntuarioNro = prontuariosic }
        //        };
        //    return View("AltaModificacionAFIS", afis);
        //}

    }
}

ISICWeb/Areas/Antecedentes/Views/AntecedentesAfis/AltaModificacionAFIS.cshtml
@model ISICWeb.Areas.Antecedentes.Models.AFISViewModel
@{ string url = Session["CurrentUrl"] != null ? Session["CurrentUrl"].ToString() : @Url.Action("Index","Antecedentes"); }

@using (Ajax.BeginForm("GuardarDatosAFIS", "Antecedentes",
  new AjaxOptions
                {
                    UpdateTargetId = "divValidation",
                    HttpMethod = "Post",
                    OnBegin = "onGuardarBegin",
                    OnComplete = "onGuardarComplete",
                    OnSuccess = "onGuardarSuccess"
                },
                new { id = "frmGuardarDatosAfis" }))
{    @Html.AntiForgeryToken()
    <div class="row wow fadeInDown animated">
        <ol class="breadcrumb hidden-xs tile-light" style="float: left !important">
            <li>@Html.ActionLink("Búsqueda", "Index", "Antecedentes")</li>
            <li><a href="@url">Resultados</a></li>
            <li>@Html.ActionLink("Listado AFIS", "BuscarFichasAFIS", new {prontuariosic = Model.Prontuario.ProntuarioNro}, new {onclick = "showPageLoadingSpinner();"})</li>
            <li class="active">Carga AFIS</li>
        </ol>
    </div>
    
        <div class=" center wow fadeInDown animated tile-light">
            <h3>
                Carga datos del AFIS
            </h3>
        </div>


        if (Model != null)
        {
        Html.RenderAction("MostrarDatosImputado", "Antecedentes", new { idIdgxprontuario = Model.Id });

        }
        <div class="panel panel-default tile wow fadeInDown animated" style="margin-bottom: 80px;">
            <div class="panel-heading">
                @if (Model.Id > 0)
            {
                    <h4><b style="color:red">Modificación</b> Datos del AFIS</h4>
            }
            else
            {
                    <h4>Carga Nuevos Datos del AFIS</h4>
            }
            </div>
            <div class="panel-body">


                <div class="row wow fadeInDown animated">

                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.NIF, htmlAttributes: new { @class = "control-label  " })
                        @Html.EditorFor(model => model.NIF, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NIF, "", new { @class = "text-danger" })
                    </div>


                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label  " })
                        @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })



                    </div>

                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label  " })
                        @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row wow fadeInDown animated">

                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.idClaseSexo, "Sexo", htmlAttributes: new { @class = "control-label  " })
                        @*@Html.HiddenFor(model=>model.Sexo.descripcion)*@
                        @Html.DropDownListFor(model => model.idClaseSexo, Model.SexoList as IEnumerable<SelectListItem>, new { @class = "form-control" })


                    </div>
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.idTipoDoc, htmlAttributes: new { @class = "control-label  " })
                        @Html.DropDownListFor(model => model.idTipoDoc, Model.TipoDocList as IEnumerable<SelectListItem>, new { @class = "form-control" })


                    </div>
                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.DNI, htmlAttributes: new { @class = "control-label  " })
                        @Html.EditorFor(model => model.DNI, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DNI, "", new { @class = "text-danger" })
                    </div>

                  
                </div>

                <div class="row wow fadeInDown animated">

                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.Clase, htmlAttributes: new { @class = "control-label  " })
                        @Html.EditorFor(model => model.Clase, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Clase, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-xs-4">
                        @Html.LabelFor(model => model.CTL, htmlAttributes: new { @class = "control-label  " })
                        @Html.EditorFor(model => model.CTL, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CTL, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12" id="divValidation">
                        @Html.HiddenFor(model=>model.Prontuario.ProntuarioNro)
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id)

                    </div>
                </div>

            </div>
        </div>
        <nav class="navbar navbar-default navbar-fixed-bottom tile-dark">
            <div class="row">
                <div class="  col-sm-3 col-xs-4">
                    @Html.ActionLink("Volver", "BuscarFichasAFIS", new { prontuariosic = Model.Prontuario.ProntuarioNro }, new { @class = "btn btn-alt btn-lg", onclick = "showPageLoadingSpinner();" })



                </div>
                <div class="col-md-3 col-md-offset-2 col-sm-4 col-xs-8">
                    <div class="row ">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <input type="submit" value="Guardar" class="btn btn-alt btn-lg" />

                        </div>
                    </div>
                </div>

            </div>

        </nav>
        }

        @section scripts
{
            <script>
                //GUARDAR DATOS AFIS
                function onGuardarBegin() {
                    loader("Guardando, espere un momento...");
                }

                function onGuardarComplete() {
                    $.unblockUI();
                }

                function onGuardarSuccess(data) {
                    if (data == "") {
                        //alertify.success("Alta exitosa");
                        var url = '@Url.Content("BuscarFichasAFIS")?prontuariosic=@Model.Prontuario.ProntuarioNro';
                        alertify.alert("Exito", "<i class='Exito'>Carga Exitosa</i>").set({
                            onclose: function () {
                                showPageLoadingSpinner();
                                location.href = url;

                            }
                        });

                        //$("#btnNuevoDelito").removeClass("hidden");
                        //$("#cartelSinDelitos").addClass("hidden");
                        //$("#Id").val($("#idIdgxdatospersonales").val());

                    } else {
                        alertify.error("Error en la carga");
                        //$("#btnNuevoDelito").addClass("hidden");
                        $("#cartelSinDelitos").removeClass("hidden");
                    }
                }


                $(document).ready(function () {
                    $("#navFooter").hide();
                    $("#Clase").mask("9999");
                });
            </script>
        }

ISICWeb/Areas/Antecedentes/Views/AntecedentesAfis/ListadoAFIS.cshtml
@model ISIC.Entities.Prontuario
@{ string url = Session["CurrentUrl"] != null ? Session["CurrentUrl"].ToString() : @Url.Action("Index", "Antecedentes"); }

<div class="row wow fadeInDown animated">
    <ol class="breadcrumb hidden-xs tile-light" style="float: left !important">
        <li>@Html.ActionLink("Búsqueda", "Index", "Antecedentes")</li>
        <li><a href="@url">Resultados</a></li>
        <li class="active">Lista AFIS</li>
    </ol>
</div>
<div class=" center wow fadeInDown animated tile-light">
    <h1>
        Fichas de AFIS
    </h1>
</div>
<div class="tile   wow fadeInDown animated">
    @{
        Html.RenderAction("MostrarDatosImputado", "Antecedentes", new { prontuarioSic = Model.ProntuarioNro });

    }
</div>


<div class="tile tile  wow fadeInDown animated" style="margin-bottom: 80px;">

    <div class="panel panel-default ">
        <div class="panel-heading">
            <h4>
                Listado de fichas de AFIS
            </h4>
        </div>
    </div>

    <div class="panel-body">
        <div class="row">
            <div class="col-md-12">
                <table id="tablaAFIS" class="table  table-bordered table-hover  table-striped  tabla" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>
                                NIF
                            </th>
                            <th>
                            Apellido
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Documento Nro.
                            </th>
                            <th>
                                Clase
                            </th>
                            
                            <th></th>
                        </tr>

                    </thead>
                    <tbody>
                        @if (Model != null && Model.DatosAFIS != null)
                        {
                            foreach (var item in Model.DatosAFIS.Where(x => x.Baja != true))
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NIF)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Apellido)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Nombre)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DNI)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Clase)
                                    </td>
                                    
                                    <td style="text-align: right">
                                        @Html.ActionLink("Editar", "AltaModificacionAFIS", new {prontuariosic=Model.ProntuarioNro,idAfis=item.Id }, new { @class = "btn btn-alt btn-sm " })
                                        <input type="button" class="btn btn-alt btn-sm" id="btnBorrarAFIS" data-id="@item.Id" value="Borrar" />
                                    </td>
                                </tr>
                            }
                        }

                    </tbody>
                </table>
                <div class="row">
                    <div class="col-md-12">
                        <div class="pull-right">

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>



</div>

@section footer
{
    <div class="col-md-2 col-sm-2 col-xs-6">
        @*<a class="btn btn-lg btn-alt volver" href='#' onclick=' ' title=" volver" type="button">
                Volver
            </a>*@
        <a class="btn btn-lg btn-alt volver" href='@url' title=" volver" onclick="showPageLoadingSpinner();" type="button">
            Volver
        </a>
    </div>
    <div class="col-md-6 col-md-offset-4 col-sm-2 col-sm-offset-4 col-xs-6">
        @if (Model != null)
        {
            @Html.ActionLink("Nuevo", "AltaModificacionAFIS", new{prontuariosic=Model.ProntuarioNro}, new { @class = "btn btn-alt btn-lg ", onclick = "showPageLoadingSpinner();" })
        }


    </div>

}


<script>
    $(document).ready(function () {
        $('#tablaAFIS').dataTable({
            "dom": '<"row"<"col-md-12"ipT>><"clear">rt<"bottom"><"clear">',
            "tableTools": {
                "aButtons": [],

            },
            "columnDefs": [
                {
                    "targets": 4,
                    "sortable": false
                }
            ],
            "language": {
                "sProcessing": "Procesando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "No se encontraron resultados",
                "sEmptyTable": "Ningún dato disponible en esta tabla",
                "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "sInfoThousands": ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst": "Primero",
                    "sLast": "Último",
                    "sNext": "Siguiente",
                    "sPrevious": "Anterior"
                },
                "oAria": {
                    "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                    "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                }
            }
        });
        $('#tablaAFIS tbody').on('click', '#btnBorrarAFIS', function () {

            var id = $(this).data("id");
            var table = $('#tablaAFIS').DataTable();
            var row = table.row($(this).parents('tr'));

            alertify.confirm("Borrar ficha de AFIS", "Seguro que desea borrar?", function () {

                var url = '@Url.Action("BorrarFichasAFIS","AntecedentesAfis")/' + encodeURI(id);
                $.get(url, null, function (data) {
                    if (data === "True") {
                        row.remove().draw();
                        alertify.success("Ficha de AFIS borrada correctamente");


                    } else {
                        alertify.error("Error al borrar");
                    }
                });

            }, null)
         .set('labels', { cancel: 'Cancelar' })
         .set('defaultFocus', 'cancel');
        });

    });


</script>

ISICWeb/Areas/Antecedentes/Views/AntecedentesAfis/_SummaryErrorAfis.cshtml
@model ISICWeb.Areas.Antecedentes.Models.AFISViewModel
@Html.HiddenFor(x => x.Prontuario.Id)
@Html.HiddenFor(x => x.Id)
@Html.HiddenFor(x => x.Prontuario.ProntuarioNro)
@Html.ValidationSummary()